app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('users_cart/', views.UserCartView.as_view(), name='users_cart'), 

    # path('cart_add/<slug:product_slug>/', views.CardAdd.as_view(), name='cart_add'), 
    # path('cart_add/', views.CartAdd.as_view(), name='cart_add'), 
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'), 

    path('cart_change/<int:cart_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.CreateOrderView.as_view(), name='create_order'), 
]

carts/models.py
from django.db import models

from goods.models import Products


class  CartQueryset(models.QuerySet):
    
    def total_price(self):
        return sum(cart.product_price() for cart in self)
    
    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Cart(models.Model):
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = 'корзину'
        verbose_name_plural = 'Корзины'

    objects = CartQueryset().as_manager()

    def product_price(self):
        return round(self.product.sell_price() * self.quantity, 2)
    
    def __str__(self):
        return f'Анонимная корзина | {self.product.name} | Количество {self.quantity}'
    
    

carts/views.py
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import ListView

from carts.models import Cart
from goods.models import Products

class UserCartView(ListView):
    template_name = 'carts/cart.html'   
    context_object_name = 'carts'

    def get_queryset(self):
        carts = Cart.objects.filter(session_key=self.request.session.session_key)
        return carts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваша корзина:Sattiyas - Fashion'
        return context


# class CardAdd(View):
#     def post(self, request):
#         product = Products.objects.get(slug=product_slug)

#         carts = Cart.objects.filter(session_key=request.session.session_key, product=product)
#         if carts.exists():
#             cart = carts.first()
#             if cart:
#                 cart.quantity += 1
#                 cart.save()
#             else:
#                 Cart.objects.create(session_key=request.session.session_key, product=product, quantity=1)
        
#         return redirect(request.META['HTTP_REFERER'])

def cart_add(request, product_slug):

    product = Products.objects.get(slug=product_slug)
    
    carts = Cart.objects.filter(session_key=request.session.session_key, product=product)

    if carts.exists():
        cart = carts.first()
        if cart:
            cart.quantity += 1
            cart.save()
    else:
        Cart.objects.create(session_key=request.session.session_key, product=product, quantity=1)


    return redirect(request.META['HTTP_REFERER']) 




def cart_change(request, cart_id):

    quanti = request.GET.get('quantity', None)
    cart = Cart.objects.get(id=cart_id)
    
    quanti = int(quanti)
    x = cart.quantity + quanti
    if x == 0:
        cart.delete()
    else:
        cart.quantity += 1
        cart.save()        

    return redirect(request.META['HTTP_REFERER']) 


def cart_remove(request, cart_id):
    cart = Cart.objects.get(id=cart_id)
    cart.delete()
    return redirect(request.META['HTTP_REFERER']) 
    

carts/templates/carts/cart.html
{% extends "base.html" %}
{% load static %}

{% block content_one %} 
  <!-- Start Cart Page Heading -->
  <section>
    <div class="container">
      <div class="cs_height_80 cs_height_lg_60"></div>
      <div class="cs_shop_page_heading text-center">
        <h1 class="cs_fs_50 cs_bold">Shopping Cart</h1>
        <div class="cs_shop_breadcamp cs_medium">
          <a href="{% url "main:index" %}">Home</a>
          <svg width="17" height="8" viewBox="0 0 17 8" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M16.3536 4.35355C16.5488 4.15829 16.5488 3.84171 16.3536 3.64645L13.1716 0.464467C12.9763 0.269205 12.6597 0.269205 12.4645 0.464467C12.2692 0.659729 12.2692 0.976312 12.4645 1.17157L15.2929 4L12.4645 6.82843C12.2692 7.02369 12.2692 7.34027 12.4645 7.53553C12.6597 7.7308 12.9763 7.7308 13.1716 7.53554L16.3536 4.35355ZM-4.37114e-08 4.5L16 4.5L16 3.5L4.37114e-08 3.5L-4.37114e-08 4.5Z" fill="#5E5E5E"/>
          </svg>            
          <span>Cart</span>
        </div>
      </div>
      <div class="cs_height_80 cs_height_lg_60"></div>
    </div>
  </section>
  <!-- End Cart Page Heading -->
  <!-- Start Cart -->
  <div class="container">
    <div class="row">
      <div class="col-xl-8">
        <div class="table-responsive">
          <table class="cs_cart_table">
            <thead>
              <tr>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Subtotal</th>
                <th></th>
              </tr>
            </thead>
            <tbody>

            {% for cart in carts %}
              <tr>
                <td>
                  <div class="cs_cart_table_media">
                    <img src="{{cart.product.image.url}}" alt="{{cart.product.name}}">
                    <h3>{{cart.product.name}}</h3>
                  </div>
                </td>
                <td>{{cart.product.sell_price}}</td>
                <td>
                  <form class="cs_quantity" action="{% url "carts:cart_change" cart.id  %}" method="get">
                    <button type="submit" class="cs_quantity_btn cs_increment" name="quantity" value="+1"><i class="fa-solid fa-angle-up"></i></button>
                      <span class="cs_quantity_input" value={{cart.quantity}}>{{cart.quantity}}</span>
                    <button type="submit" class="cs_quantity_btn cs_decrement" name="quantity" value="-1"><i class="fa-solid fa-angle-down"></i></button>
                  </form>
                </td>
                <td>{{cart.product_price}}</td>
                <td class="text-center">
                  <a href="{% url "carts:cart_remove" cart.id %}" class="cs_cart-table-close"><i class="fa-solid fa-xmark"></i></a>
                </td>
              </tr>
            {% endfor %}

            </tbody>
          </table>
        </div>
        <div class="cs_height_30 cs_height_lg_30"></div>
      </div>
      <div class="col-xl-4">
        <div class="cs_shop-side-spacing">
          <div class="cs_shop-card">
            <div class="cs_height_30 cs_height_lg_30"></div>
            <h2 class="cs_fs_21 cs_medium">Cart Totals</h2>
            <table class="cs_medium">
              <tbody>
                <tr>
                  <td>Quantity</td>
                  <td class="text-end">{{carts.total_quantity}}</td>
                </tr>
                <tr>
                  <td>Total</td>
                  <td class="text-end">${{carts.total_price}}</td>
                </tr>
              </tbody>
            </table>
            <div class="cs_height_30 cs_height_lg_30"></div>
            {% if carts %}
              <a href="{% url "orders:create_order" %}" class="cs_btn cs_style_1 cs_fs_16 cs_medium w-100">Procced To Checkout</a>
            {% endif %}
          </div>
          <div class="cs_height_30 cs_height_lg_30"></div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}  