app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('users_cart/', views.UserCartView.as_view(), name='users_cart'), 

    # path('cart_add/<slug:product_slug>/', views.CardAdd.as_view(), name='cart_add'), 
    # path('cart_add/', views.CartAdd.as_view(), name='cart_add'), 
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'), 

    path('cart_change/<int:cart_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

orders/urls.py
from django.urls import path

from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.CreateOrderView.as_view(), name='create_order'), 
]

orders/models.py
from django.db import models
from django.template.defaultfilters import first
from goods.models import Products


    
class Order(models.Model):

    # информация о пользователе при заказе
    first_name = models.CharField(max_length=150, null=True, blank=False, verbose_name='Имя')
    last_name = models.CharField(max_length=150,  null=True, blank=False, verbose_name='Фамилия')
    #company_name = models.CharField(max_length=150, blank=True, verbose_name='Название компании')
    delivery_address = models.TextField(max_length=400, null=True, blank=False, verbose_name="Адресс доставки")
    #city = models.CharField(max_length=150, null=True, blank=False, verbose_name='Город')
    index_cod = models.CharField(max_length=150, null=True, blank=False, verbose_name='Индекс')
    phone_number = models.CharField(max_length=20, null=True, blank=False, verbose_name="Номер телефона")
    email = models.CharField(max_length=150, null=True, blank=False, verbose_name='Почта')
    additional_inforation = models.TextField(max_length=1000, blank=True, verbose_name="Дополнительная информация")


    # системная информация о заказе
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default="В обработке", verbose_name="Статус заказа")
 
    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ № {self.pk} | Покупатель {self.last_name} {self.first_name}"

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Проудукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveBigIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданный товар"
    
    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"
    

orders/forms.py
import re
from django import forms

class CreateOrderForms(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    delivery_address = forms.CharField()
    index_cod = forms.CharField()
    phone_number = forms.CharField()
    email = forms.CharField()
    additional_inforation = forms.CharField(required=False)  




    #валидаторы  
    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")
    
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Неверный формат номера")

        return data

orders/views.py
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView


from carts.models import Cart
from orders.forms import CreateOrderForms
from orders.models import Order, OrderItem


class CreateOrderView(FormView):
    template_name = "orders/create_order.html"
    form_class = CreateOrderForms
    success_url = reverse_lazy('main:index')

    def form_valid(self, form):
        try:
            with transaction.atomic():
                cart_items = Cart.objects.filter(
                    session_key=self.request.session.session_key
                )

                if cart_items.exists():
                    order = Order.objects.create(
                        first_name=form.cleaned_data["first_name"],
                        last_name=form.cleaned_data["last_name"],
                        delivery_address=form.cleaned_data["delivery_address"],
                        index_cod=form.cleaned_data["index_cod"],
                        phone_number=form.cleaned_data["phone_number"],
                        email=form.cleaned_data["email"],
                        additional_inforation=form.cleaned_data[
                            "additional_inforation"
                        ],
                    )

                    for cart_item in cart_items:
                        product = cart_item.product
                        name = cart_item.product.name
                        price = cart_item.product.sell_price()
                        quantity = cart_item.quantity

                        if product.quantity < quantity:
                            raise ValidationError(
                                f"Недостаточное количество товара {name} наскладе \
                                                    В наличии - {product.quantity}"
                            )

                        OrderItem.objects.create(
                            order=order,
                            product=product,
                            name=name,
                            price=price,
                            quantity=quantity,
                        )
                        product.quantity -= quantity
                        product.save()

                    cart_items.delete()

                    messages.success(self.request, "Заказ оформлен!")
                    return redirect("main:index")
        except ValidationError as e:
            messages.success(self.request, str(e))
            return redirect("carts:users_cart")

    def form_invalid(self, form):
        messages.success(self.request, "Упс, что-то не так!")
        return redirect("carts:users_cart")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Оформление заказа'
        context['carts'] = Cart.objects.filter(session_key=self.request.session.session_key)
        return context

# def create_order(request):

#     if request.method == "POST":
#         form = CreateOrderForms(data=request.POST)
#         if form.is_valid():
#             try:
#                 with transaction.atomic():

#                     cart_items = Cart.objects.filter(
#                         session_key=request.session.session_key
#                     )

#                     if cart_items.exists():
#                         order = Order.objects.create(
#                             first_name=form.cleaned_data["first_name"],
#                             last_name=form.cleaned_data["last_name"],
#                             delivery_address=form.cleaned_data["delivery_address"],
#                             index_cod=form.cleaned_data["index_cod"],
#                             phone_number=form.cleaned_data["phone_number"],
#                             email=form.cleaned_data["email"],
#                             additional_inforation=form.cleaned_data[
#                                 "additional_inforation"
#                             ],
#                         )

#                         for cart_item in cart_items:
#                             product = cart_item.product
#                             name = cart_item.product.name
#                             price = cart_item.product.sell_price()
#                             quantity = cart_item.quantity

#                             if product.quantity < quantity:
#                                 raise ValidationError(
#                                     f"Недостаточное количество товара {name} наскладе \
#                                                     В наличии - {product.quantity}"
#                                 )

#                             OrderItem.objects.create(
#                                 order=order,
#                                 product=product,
#                                 name=name,
#                                 price=price,
#                                 quantity=quantity,
#                             )
#                             product.quantity -= quantity
#                             product.save()

#                         cart_items.delete()

#                         messages.success(request, "Заказ оформлен!")
#                         return redirect("main:index")
#             except ValidationError as e:
#                 messages.success(request, str(e))
#                 return redirect("carts:users_cart")

#         else:
#             messages.success(request, "Упс, что-то не так!")

#     else:
#         form = CreateOrderForms()

#     carts = Cart.objects.filter(session_key=request.session.session_key)
#     context = {
#         "carts": carts,
#         "form": form,
#         "order": True,
#     }

#     return render(request, "orders/create_order.html", context=context)

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}

{% block content_one %} 

  <!-- Start Cart Page Heading -->
  <section>
    <div class="container">
      <div class="cs_height_80 cs_height_lg_60"></div>
      <div class="cs_shop_page_heading text-center">
        <h1 class="cs_fs_50 cs_bold">Checkout</h1>
        <div class="cs_shop_breadcamp cs_medium">
          <a href="{% url "main:index" %}">Home</a>
          <svg width="17" height="8" viewBox="0 0 17 8" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M16.3536 4.35355C16.5488 4.15829 16.5488 3.84171 16.3536 3.64645L13.1716 0.464467C12.9763 0.269205 12.6597 0.269205 12.4645 0.464467C12.2692 0.659729 12.2692 0.976312 12.4645 1.17157L15.2929 4L12.4645 6.82843C12.2692 7.02369 12.2692 7.34027 12.4645 7.53553C12.6597 7.7308 12.9763 7.7308 13.1716 7.53554L16.3536 4.35355ZM-4.37114e-08 4.5L16 4.5L16 3.5L4.37114e-08 3.5L-4.37114e-08 4.5Z" fill="#5E5E5E"/>
          </svg>
          <a href="{% url "carts:users_cart" %}">Cart</a>
          <svg width="17" height="8" viewBox="0 0 17 8" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M16.3536 4.35355C16.5488 4.15829 16.5488 3.84171 16.3536 3.64645L13.1716 0.464467C12.9763 0.269205 12.6597 0.269205 12.4645 0.464467C12.2692 0.659729 12.2692 0.976312 12.4645 1.17157L15.2929 4L12.4645 6.82843C12.2692 7.02369 12.2692 7.34027 12.4645 7.53553C12.6597 7.7308 12.9763 7.7308 13.1716 7.53554L16.3536 4.35355ZM-4.37114e-08 4.5L16 4.5L16 3.5L4.37114e-08 3.5L-4.37114e-08 4.5Z" fill="#5E5E5E"/>
          </svg>            
          <span>Checkout</span>
        </div>
      </div>
      <div class="cs_height_80 cs_height_lg_60"></div>
    </div>
  </section>
  <!-- End Cart Page Heading -->

  <!-- Start Checkout -->
  <form action="{% url "orders:create_order" %}" method="post">
    {% csrf_token %}
    <div class="container">
      <div class="row">
        
        <div class="col-xl-7">
          <div class="cs_height_40 cs_height_lg_40"></div>
          <h2 class="cs_checkout-title cs_fs_28">Billing Details</h2>
          <div class="cs_height_45 cs_height_lg_40"></div>
          <div class="row">
            <div class="col-lg-6">
              <label for="id_first_name" class="cs_shop-label">First Name *</label>
              <input type="text" class="cs_shop-input" id="id_first_name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" name="first_name" required>
              {% if form.first_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
              {% endif %}          
            <div data-lastpass-icon-root="true" style="position: relative !important; height: 0px !important; width: 0px !important; float: left !important;"></div></div>
            <div class="col-lg-6">
              <label for="id_last_name" class="cs_shop-label">Last Name *</label>
              <input type="text" class="cs_shop-input" id="id_last_name" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" name="last_name" required>
              {% if form.last_name.errors %}
                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
              {% endif %}
            </div>
          </div>
          <div class="col-lg-12">
            <label for="id_delivery_address" class="cs_shop-label">Address *</label>
            <input type="text" class="cs_shop-input" id="id_delivery_address" value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}" name="delivery_address" required>
            {% if form.delivery_address.errors %}
              <div class="alert alert-danger alert-dismissible fade show">{{form.delivery_address.errors}}</div>
            {% endif %}
          </div>
          <div class="col-lg-12">
            <label for="id_index" class="cs_shop-label">ZIP Code *</label>
            <input type="text" class="cs_shop-input" id="id_index" value="{% if form.index_cod.value %}{{ form.index_cod.value }}{% endif %}" name="index_cod" required>
            {% if form.index.errors %}
              <div class="alert alert-danger alert-dismissible fade show">{{form.index.errors}}</div>
           {% endif %}
          </div>
          <div class="col-lg-12">
            <label for="id_phone" class="cs_shop-label">Phone *</label>
            <input type="text" class="cs_shop-input" id="id_phone" value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
            placeholder="В формате: XXX-XXX-XX-XX" name="phone_number" required>
            {% if form.phone_number.errors %}
              <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
           {% endif %}
          </div>
          <div class="col-lg-12">
            <label for="id_email" class="cs_shop-label">Email address *</label>
            <input type="email" class="cs_shop-input" id="id_email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}" name="email" required>
            {% if form.email.errors %}
              <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
            {% endif %}
          </div>
 
          <div class="cs_height_45 cs_height_lg_45"></div>
          <h2 class="cs_checkout-title">Additional information</h2>
          <div class="cs_height_25 cs_height_lg_25"></div>
          <label for="id_additional_inforation" name="additional_inforation" class="cs_shop-label">Order notes (optional)</label>
          <textarea  class="cs_shop-input" id="id_additional_inforation" cols="30" rows="6" value="{% if form.additional_inforation.value %}{{ form.additional_inforation.value }}{% endif %}" name="additional_inforation"></textarea>
          {% if form.additional_inforation.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{form.additional_inforation.errors}}</div>
          {% endif %}
          <div class="cs_height_30 cs_height_lg_30"></div>
          <!-- Корзина на странице оформления заказа -->      
        </div> 
        <div class="col-xl-5">
          <div class="cs_shop-side-spacing">
            <div class="cs_shop-card">
              <h2 class="cs_fs_21">Your order</h2>
              <table>
                <tbody>
                  <tr class="cs_semi_bold">
                    <td>Products</td>
                    <td class="text-end">Amount</td>
                  </tr>
                  {% for cart in carts %}
                    <tr>
                      <td>{{cart.product.name}}</td>
                      <td class="text-end">${{cart.product_price}}</td>
                    </tr>
                  {% endfor %}
                  <tr>
                    <td class="cs_semi_bold">Quantity</td>
                    <td class="text-end">{{carts.total_quantity}}</td>
                  </tr>
                  <tr class="cs_semi_bold">
                    <td>Total</td>
                    <td class="text-end">${{carts.total_price}}</td>
                  </tr>
                </tbody>
              </table>
              <!-- Конец корзины на странице оформления заказа -->  
              <!-- Оставить заказ + ссылка на оплату -->              
              <div class="cs_height_30 cs_height_lg_30"></div>
              <button type="submit" href="{% url "orders:create_order" %}" class="cs_btn cs_style_1 cs_fs_16 cs_medium w-100">Place Order</button>
            </div>
          </div>
        </div>
        
      </div>
    </div>
  </form>    
  <!-- Конец еста для заказа и ссылки на оплату -->      
{% endblock  %}