app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('users_cart/', views.UserCartView.as_view(), name='users_cart'), 

    # path('cart_add/<slug:product_slug>/', views.CardAdd.as_view(), name='cart_add'), 
    # path('cart_add/', views.CartAdd.as_view(), name='cart_add'), 
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'), 

    path('cart_change/<int:cart_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'), 
    path('', views.CatalogView.as_view(), name='index'), 
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product'),
]

goods/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name = 'категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name
    
class People_categorys(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Пол')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'people_category'
        verbose_name = 'пол'
        verbose_name_plural = 'Полы'

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0, max_digits=7, decimal_places=0, verbose_name='Цена')
    discount = models.DecimalField(default=0, max_digits=4, decimal_places=0, verbose_name='Скидка в %')
    quantity = models.PositiveBigIntegerField(default=0, verbose_name='Количество')
    people_category = models.ForeignKey(to=People_categorys, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Пол')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')
    sizе = models.CharField(max_length=150, blank=True, null=True, verbose_name='Размер')
    brand = models.CharField(max_length=150, blank=True, null=True, verbose_name='Бренд')
    rating = models.CharField(max_length=150, blank=True, null=True, verbose_name='Рейтинг')
    featured_item = models.BooleanField(blank=True, null=True, verbose_name='Рекомендовано')
    new_item = models.BooleanField(blank=True, null=True, verbose_name='Новинка')
    top_item = models.BooleanField(blank=True, null=True, verbose_name='Лучшее')

    

    class Meta:
        db_table = 'product'
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        ordering = ("id",)

    def __str__(self):
        return f'{self.name} количество - {self.quantity} | Рек:{self.featured_item} | Новинка: {self.new_item} | Лучшее: {self.top_item}'

    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    

 
    def display_id(self):
        return f'{self.id:05}'
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        
        return self.price
    
        
    

goods/views.py
from re import S
from typing import Any
from django.db.models.base import Model as Model

from django.db.models.query import QuerySet
from django.views.generic import DetailView, ListView

from goods.models import Products
from goods.utils import q_search

rating_list = []


class CatalogView(ListView):
    model = Products
    template_name = "goods/catalog.html"
    context_object_name = "goods"
    paginate_by = 8

    def get_queryset(self):
        # переменные фильтров radio (размер и бренд)
        size = self.request.GET.get("size")
        brand = self.request.GET.get("brand")
        # переменная поиска
        query = self.request.GET.get("q")
        # переменные фильтвров chekbox (рейтинг, пол, категория одежды)
            # переменные людей
        x = 3
        people_status = False
        people_list = []
        while x != 0:
            people_list.append(self.request.GET.get("people" + str(x)))
            x -= 1
        if (
            "Женское" in people_list
            or "Мужское" in people_list
            or "Детское" in people_list
        ):
            people_status = True
        else:
            people_status = False
            # конец переменной людей
            # переменные категорий одежды
        x = 7
        clothes_status = False
        clothes_list = []
        while x != 0:
            clothes_list.append(self.request.GET.get("clothes" + str(x)))
            x -= 1
        if (
            "Платья" in clothes_list
            or "Топы" in clothes_list
            or "Джинсы" in clothes_list
            or "Футболки" in clothes_list
            or "Костюмы" in clothes_list
            or "Рубашки" in clothes_list
            or "Штаны" in clothes_list
        ):
            clothes_status = True
        else:
            clothes_status = False
            # конец переменной категорий одежды
            # переменные рейтингов
        x = 5
        rating_status = False
        rating_list = []
        while x != 0:
            rating_list.append(self.request.GET.get("rating" + str(x)))
            x -= 1
        if (
            "1" in rating_list
            or "2" in rating_list
            or "3" in rating_list
            or "4" in rating_list
            or "5" in rating_list
        ):
            rating_status = True
        else:
            rating_status = False
            # конец перемееной рейтингов
            # переменные фильтров
        order_by = self.request.GET.get("order_by")
            # конец переменных фильтров

            # формирование запроса в БД
        if query:
            goods = q_search(query)
        else:
            goods = super().get_queryset()
        if size and size != "Default":
            goods = super().get_queryset().filter(sizе__exact=size)

        if brand and brand != "Default":
            goods = super().get_queryset().filter(brand__exact=brand)

        if people_status:
            goods = (
                super().get_queryset().filter(people_category__name__exact=people_list[2])
                | super().get_queryset().filter(people_category__name__exact=people_list[1])
                | super().get_queryset().filter(people_category__name__exact=people_list[0])
            )

        if clothes_status:
            goods = (
                super().get_queryset().filter(category__name__exact=clothes_list[6])
                | super().get_queryset().filter(category__name__exact=clothes_list[5])
                | super().get_queryset().filter(category__name__exact=clothes_list[4])
                | super().get_queryset().filter(category__name__exact=clothes_list[3])
                | super().get_queryset().filter(category__name__exact=clothes_list[2])
                | super().get_queryset().filter(category__name__exact=clothes_list[1])
                | super().get_queryset().filter(category__name__exact=clothes_list[0])
            )

        if rating_status:
            goods = (
                super().get_queryset().filter(rating__exact=rating_list[4])
                | super().get_queryset().filter(rating__exact=rating_list[3])
                | super().get_queryset().filter(rating__exact=rating_list[2])
                | super().get_queryset().filter(rating__exact=rating_list[1])
                | super().get_queryset().filter(rating__exact=rating_list[0])
            )

        if order_by and order_by != "default":
            goods = goods.order_by(order_by)
            # запрос сформирован, возврат результата
        
        return goods

    def get_context_data(self, **kwargs):

        goods = self.get_queryset()
        goods_count = len(goods)
        goods_status = True
        goods_all_count = 8
        if goods_count < goods_all_count:
            goods_all_count = goods_count
            goods_status = False

        context = super().get_context_data(**kwargs)
        context["title"] = "Каталог - Sattiyas - Fashion"
        context["goods_count"] = goods_count
        context["goods_all_count"] = goods_all_count
        context["goods_status"] = goods_status

        return context


class ProductView(DetailView):

    template_name = "goods/product.html"
    slug_url_kwarg = "product_slug"
    context_object_name = "product"

    def get_object(self, queryset=None):
        product = Products.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = self.object.name 
        context["top_items"] = Products.objects.filter(top_item=True)
        return context

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}


{% block content_one %} 
  <!-- Start single product -->
  <section>
    <div class="cs_height_35 cs_height_lg_35"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-7">
          <div class="row">
            <div class="col-3">
              <div class="cs_single_product_nav slick-slider">

                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_mini">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
              </div>
            </div>
            <div class="col-9">
              <div class="cs_single_product_thumb slick-slider">
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
                <div class="cs_single_product_thumb_item">
                  <img src={{product.image.url}} alt="Thumb">
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-5">
          <div class="cs_single_product_details">
            <h2 class="cs_fs_37 cs_semibold">{{product.name}}</h2>
            <div class="cs_single_product_review">
              <div class="cs_rating_container">
                <div class="cs_rating cs_size_sm" data-rating={{product.rating}}>
                  <div class="cs_rating_percentage"></div>
                </div>
              </div>
              <span>({{product.rating}})</span>
              {% if product.quantity == 0 %}
                <span class="cs_accent_color">Нет в наличии</span></span>
              {% else %}
                <span>На складе: <span class="cs_accent_color">{{product.quantity}} шт</span></span>
              {% endif %}
            </div>
            {% if product.discount %}
              <p class="cs_product_price cs_fs_18 cs_accent_color mb-0 cs_medium"><s>${{product.price}}</s> ${{product.sell_price}} </p>
            {% else %}
              <p class="cs_product_price cs_fs_18 cs_accent_color mb-0 cs_medium">${{product.price}}</p>
            {% endif %}
            <hr>
            <div class="cs_single_product_details_text">
              <p class="mb-0">{{product.description}}</p>
            </div>
            <div class="cs_action_btns">
              <a href="{% url "cart:cart_add" product.slug %}" class="cs_btn cs_style_1 cs_fs_16 cs_medium">Add to Cart</a>
            </div>
            <ul class="cs_single_product_info">
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">ID: </b>{{product.display_id}}
              </li>
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">Categories: </b>{{product.category}}
              </li>
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">Tags: </b>{{product.people_category}}
              </li>
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">Brand: </b>{{product.brand}}
              </li>
              <li class="cs_fs_16 cs_normal">
                <b class="cs_medium">Size: </b>{{product.sizе}}
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="cs_height_70 cs_height_lg_60"></div>
      <hr>
    </div>
  </section>
  <!-- End single product -->
  <!-- Start new item store -->
     <section class="cs_slider position-relative">
    <div class="container">
      <div class="cs_section_heading cs_style_1">
        <div class="cs_section_heading_in">
          <h2 class="cs_section_title cs_fs_50 cs_bold mb-0">Top selling</h2>
        </div>
        <div class="cs_slider_arrows cs_style_2 cs_hide_mobile">
          <div class="cs_left_arrow cs_slider_arrow cs_accent_color">
            <i class="fa-solid fa-chevron-left"></i>
          </div>
          <div class="cs_right_arrow cs_slider_arrow cs_accent_color">
            <i class="fa-solid fa-chevron-right"></i>
          </div>
        </div>
      </div>
      <div class="cs_height_63 cs_height_lg_35"></div>
    </div>
     <div class="container-fluid">
      <div class="cs_slider_container" data-autoplay="0" data-loop="1" data-speed="600" data-center="0"
        data-slides-per-view="responsive" data-xs-slides="1" data-sm-slides="2" data-md-slides="2"
        data-lg-slides="3" data-add-slides="4">
        <div class="cs_slider_wrapper">
          
          {% for top_item in top_items %} 
            <div class="slick_slide_in">
              <div class="cs_product cs_style_1">
                <div class="cs_product_thumb position-relative">
                  {% if top_item.image %}
                    <img src="{{top_item.image.url}}" alt="Product Image">
                  {% else %}
                    {% static "assets/img/Image_not_found.png" %}  
                  {% endif %}

                  {% if  top_item.discount %}
                    <div class="cs_discount_badge cs_white_bg cs_fs_14 cs_primary_color position-absolute">Скидка {{top_item.discount}}%</div>
                  {% endif %}

                  <div class="cs_cart_badge position-absolute">
                  </div>
                  <a href="{% url "cart:cart_add" top_item.slug %}" class="cs_cart_btn cs_accent_bg cs_fs_16 cs_white_color cs_medium position-absolute">Add To Cart</a>
                </div>
                <div class="cs_product_info text-center">
                  <h3 class="cs_product_title cs_fs_21 cs_medium">
                    <a href="{% url "goods:product" top_item.slug %}">{{top_item.name}}</a>
                  </h3>

                {% if top_item.discount %}
                  <p class="cs_product_price cs_fs_18 cs_accent_color mb-0 cs_medium"><s>${{top_item.price}}</s> ${{top_item.sell_price}} </p>
                {% else %}
                  <p class="cs_product_price cs_fs_18 cs_accent_color mb-0 cs_medium">${{top_item.price}}</p>
                {% endif %}
                
                </div>
              </div>
            </div>
          {% endfor %} 


        </div>
      </div>
      <div class="cs_pagination cs_style_2 cs_hide_desktop"></div>
    </div>  
  </section>

  <!-- End new item store -->
  <hr>
{% endblock  %}