app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('users_cart/', views.UserCartView.as_view(), name='users_cart'), 

    # path('cart_add/<slug:product_slug>/', views.CardAdd.as_view(), name='cart_add'), 
    # path('cart_add/', views.CartAdd.as_view(), name='cart_add'), 
    path('cart_add/<slug:product_slug>/', views.cart_add, name='cart_add'), 

    path('cart_change/<int:cart_id>/', views.cart_change, name='cart_change'),
    path('cart_remove/<int:cart_id>/', views.cart_remove, name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'), 
    path('', views.CatalogView.as_view(), name='index'), 
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Laralink">
  <title>{{title}}</title>
  <!-- Favicon -->
  <link rel="shortcut icon" href="{% static "assets/img/FAVICON.svg" %}">
  <!-- Plugins css -->
  <link rel="stylesheet" href="{% static "assets/css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/fontawesome.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/slick.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/jquery-ui.min.css" %}">
  <link rel="stylesheet" href="{% static "assets/css/animated-headline.css" %}">
  <!-- Custom css -->
  <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
</head>

<body>
    <!-- Start Preloader -->
    <div class="cs_perloader">
      <div class="cs_perloader_in">
        <svg class="cs_cart_animation" role="img" aria-label="Sattiyas Preloader" viewBox="0 0 128 128" width="128px" height="128px" xmlns="http://www.w3.org/2000/svg">
          <g fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="8">
            <g class="cs_cart_track" stroke="hsla(0,10%,10%,0.1)">
              <polyline points="4,4 21,4 26,22 124,22 112,64 35,64 39,80 106,80" />
              <circle cx="43" cy="111" r="13" />
              <circle cx="102" cy="111" r="13" />
            </g>
            <g class="cs_cart_lines" stroke="currentColor">
              <polyline class="cs_cart_top" points="4,4 21,4 26,22 124,22 112,64 35,64 39,80 106,80" stroke-dasharray="338 338" stroke-dashoffset="-338" />
              <g class="cs_cart_wheel_1" transform="rotate(-90,43,111)">
                <circle class="cs_cart_wheel_stroke" cx="43" cy="111" r="13" stroke-dasharray="81.68 81.68" stroke-dashoffset="81.68" />
              </g>
              <g class="cs_cart_wheel_2" transform="rotate(90,102,111)">
                <circle class="cs_cart_wheel_stroke" cx="102" cy="111" r="13" stroke-dasharray="81.68 81.68" stroke-dashoffset="81.68" />
              </g>
            </g>
          </g>
        </svg>
        <span class="cs_perloader_text">Welcome to Sattiyas. Loading...</span>
      </div>
    </div>
    <!-- End Preloader -->
      <!-- Start header -->
  <header class="cs_site_header cs_style_1 cs_color_1 cs_primary_bg cs_site_header_full_width cs_sticky_header">
    <div class="cs_top_header cs_primary_color">
      <div class="container-fluid">
        <div class="cs_top_header_in">
          <div class="cs_top_header_left">
            <p class="cs_medium mb-0">Support : product@sattiyas.com</p>
          </div>
          <div class="cs_top_header_center">
            <div class="cd-headline slide">
              <span class="cd-words-wrapper text-center">
                <b class="cs_text_slide cs_medium is-visible">
                  <span>100% Happy return policy</span>
                  <span>
                    <a href="about.html" class="cs_text_slide_btn">Learn More</a>
                  </span>
                </b>
                <b class="cs_text_slide cs_medium">
                  <span>Big sale offer with 50%</span>
                  <span>
                    <a href="shop.html" class="cs_text_slide_btn">Learn More</a>
                  </span>
                </b>
                <b class="cs_text_slide cs_medium">
                  <span>New arrival item for you</span>
                  <span>
                    <a href="shop.html" class="cs_text_slide_btn">Learn More</a>
                  </span>
                </b>
              </span>
            </div>
          </div>
          <div class="cs_top_header_right">
            <p class="cs_medium mb-0">Mon-Fri Open : 11:00 - 19:00</p>
          </div>
        </div>
      </div>
    </div>
    <div class="cs_main_header">
      <div class="container-fluid">
        <div class="cs_main_header_in">
          <div class="cs_main_header_left">
            <a class="cs_site_branding" href="{% url "main:index" %}">
              <img src="{% static "assets/img/logo.svg" %}" alt="Logo">
            </a>
          </div>
          <div class="cs_main_header_center">
            <div class="cs_nav cs_medium">
              <ul class="cs_nav_list">
                <li><a href="{% url "main:index" %}">Home</a></li>
                <li><a href="{% url "goods:index" %}">Product</a></li>
                <li><a href="{% url "carts:users_cart" %}">Cart</a></li>
                <li><a href="{% url "main:about" %}">About</a></li>
                <li><a href="{% url "main:contact" %}">Contact</a></li>
                

                {% comment "" %}
                <li class="menu-item-has-children">
                  <a href="">Pages</a>
                  <ul>                   
                    <li><a href="checkout.html">Checkout</a></li>
                    <li><a href="success.html">Success</a></li>
                  </ul>
                </li>
                {% endcomment %}

                
              </ul>
            </div>
          </div>
          <div class="cs_main_header_right">
            <div class="cs_header_action">

              <button type="button" class="cs_action_icon cs_header_search_btn">
                <i class="fa-solid fa-magnifying-glass"></i>
              </button>

              {% comment %} <a href="#" class="cs_action_icon cs_modal_btn">
                <i class="fa-regular fa-circle-user"></i>
              </a> {% endcomment %}

            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="cs_header_search_wrap">
      <div class="container">
        <div class="cs_header_search_in">
          <div class="cs_hero_search_heading">
            <h3>What are you looking for?</h3>
            <button class="cs_header_search_close" type="button"><i class="fa-solid fa-xmark"></i></button>
          </div>
          <form action="{% url "goods:search" %}" method="get" class="cs_header_search_form">
            <input type="search" name="q" placeholder="Search...">
            <button type="submit">
              <i class="fa-solid fa-magnifying-glass"></i>
            </button>
          </form>
        </div>
      </div>
    </div>
  </header>
  <div class="cs_height_140 cs_height_lg_80"></div>
  <!-- End header -->

{% block content_one %}
{% comment %} Контент {% endcomment %}
{% endblock  %}

  
  <!-- Start footer -->
  <footer class="cs_footer cs_style_1">
    <div class="cs_height_130 cs_height_lg_80"></div>
    <div class="container">
      <div class="cs_footer_main">
        <div class="row">
          <div class="col-xxl-3 col-lg-3">
            <div class="cs_footer_widget cs_text_widget">
              <p>Discover endless delights your one stop eCommerce destination.</p>
              <img src="{% static "assets/img/payment_method.svg" %}" alt="Payment">
            </div>
          </div>
          <div class="col-xxl-7 offset-xxl-2 offset-lg-1 col-lg-8">
            <div class="row">
              <div class="col-md-4">
                <div class="cs_footer_widget cs_menu_widget">
                  <h3 class="cs_footer_widget_title cs_fs_21 cs_semibold">Get to know</h3>
                  <ul>
                    <li><a href="{% url "main:about" %}">About Us</a></li>
                    <li><a href="{% url "goods:index" %}">Product</a></li>
                    <li><a href="{% url "main:contact" %}">Contact Us</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-4">
                <div class="cs_footer_widget cs_menu_widget">
                  <h3 class="cs_footer_widget_title cs_fs_21 cs_semibold">Customer Service</h3>
                  <ul>
                    <li><a href="#">Help Center</a></li>
                    <li><a href="#">Shipping & Delivery</a></li>
                    <li><a href="#">Exchange & Return</a></li>
                    <li><a href="#">Payment Method</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-md-4">
                <div class="cs_footer_widget cs_menu_widget">
                  <h3 class="cs_footer_widget_title cs_fs_21 cs_semibold">Contact Information</h3>
                  <ul class="cs_contact_info">
                    <li>Call : +00(244)14-50-774</li>
                    <li>Email : info@sattiyas.com</li>
                    <li>Mon – Fri : 11 am – 9 pm</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="cs_footer_bottom">
        <div>
          <p class="cs_copywrite_text mb-0">Copyright & 2023, All rights reserved.</p>
        </div>
        <div>
          <ul class="cs_footer_menu_widget_2">
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms of Use</a></li>
            <li><a href="#">Legal</a></li>
          </ul>
        </div>
        <div>
          <div class="cs_social_links">
            <a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a>
            <a href="https://twitter.com/" target="_blank"><i class="fa-brands fa-x-twitter"></i></a>
            <a href="https://www.youtube.com/" target="_blank"><i class="fa-brands fa-youtube"></i></a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End footer -->
  <!-- Start scroll up button -->
  <div class="cs_scrollup_btn" id="cs_scroll_btn">
    <i class="fa-solid fa-arrow-up"></i>
  </div>
  <!-- End scroll up button -->
  <!-- All script files -->
  <script src="{% static "assets/js/jquery-3.6.0.min.js" %}"></script>
  <script src="{% static "assets/js/jquery.slick.min.js" %}"></script>
  <script src="{% static "assets/js/isotope.pkg.min.js" %}"></script>
  <script src="{% static "assets/js/jquery-ui.min.js" %}"></script>
  <script src="{% static "assets/js/animated-headline.js" %}"></script>
  <script src="{% static "assets/js/main.js" %}"></script>
</body>
</html>